#cloud-config
hostname: ${vm_name_prefix}-${index}
fqdn: ${vm_name_prefix}-${index}.${domain}
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - vim
  - net-tools

write_files:
  - path: /etc/netplan/00-installer-config.yaml
    content: |
      network:
        version: 2
        ethernets:
          ens192:
            dhcp4: true

runcmd:
  - netplan apply
  - echo "Cloud-Init completed" >> /var/log/cloud-init-complete.log